reporter: "xcode"

disabled_rules:
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count

analyzer_rules:
  - explicit_self

vertical_whitespace:
  max_empty_lines: 2
  
nesting:
  type_level:
    warning: 4
    error: 6
  statement_level:
    warning: 4
    error: 8
	
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
	- id
	- ok
