name: Tests

on:
  push:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    types: [opened, synchronize, reopened, ready_for_review]
    
env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
  
jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Cancel Previous Runs
        if: github.ref != 'refs/heads/main'
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Test
        run: scripts/ci-test.sh
