# Build and deploy DocC to GitHub pages. Based off of @karwa's work here:
# https://github.com/karwa/swift-url/blob/main/.github/workflows/docs.yml
# and PointFree's work here:
# https://github.com/pointfreeco/swift-composable-architecture/blob/main/.github/workflows/documentation.yml
name: Docs

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: docs-out

      - name: Build documentation
        run: >
          rm -rf docs-out/.git;
          rm -rf docs-out/main;
          declare -a targets=("Cache", "Protected", "ShortID")
          git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | tail -n +6 | xargs -I {} rm -rf {};

          for tag in $(echo "main"; git tag -l --sort=-v:refname | grep -e "\d\+\.\d\+.0" | head -6);
          do
            for target in "${targets[@]}"
            do
              if [ -d "docs-out/$target/$tag/data/documentation/networking" ]
              then
                echo "✅ Documentation for $target / $tag already exists.";
              else
                echo "⏳ Generating documentation for $target @ $tag release.";
                rm -rf "docs-out/$target/$tag";

                git checkout .;
                git checkout "$tag";

                swift package \
                  --allow-writing-to-directory docs-out/"$target"/$tag" \
                  generate-documentation \
                  --target $target \
                  --output-path docs-out/"$target"/"$tag" \
                  --transform-for-static-hosting \
                  --hosting-base-path /swift-networking/"$target"/"$tag" \
                  && echo "✅ Documentation generated for $target @ $tag release." \
                  || echo "⚠️ Documentation skipped for $target @ $tag.";
              fi;
            done
          done

      - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
