name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci/cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Static Analysis
    if: github.event_name != 'workflow_dispatch'
    uses: danthorpe/ci/.github/workflows/static-analysis.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      matrix: >
        {
          "include": [
            {
              "os": "ubuntu-latest",
              "swift": "latest",
              "xcode": "latest"
            }
          ]
        }

  swift-package-test:
    name: Test Swift Package
    uses: danthorpe/ci/.github/workflows/swift-package.yml@main
    secrets: inherit
    with:
      matrix: >
        {
          "include": [
            {
              "os": "macos-14",
              "swift": "5.9",
              "xcode": "15.1"
            },
            {
              "os": "macos-14",
              "swift": "5.10",
              "xcode": "15.3"
            },
            {
              "os": "ubuntu-latest",
              "swift": "5.10"
            }
          ]
        }

  ci:
    name: CI
    if: github.event_name == 'push'
    needs: [analysis, swift-package-test]
    uses: danthorpe/ci/.github/workflows/ci.yml@main
