name: Tests

on:
  push:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**.md'
      - 'README.md'
    types: [opened, synchronize, reopened, ready_for_review]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Test
        run: .scripts/ci-test.sh
